# Generated by Django 3.0.5 on 2020-07-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200503_2348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
