# Generated by Django 3.0.5 on 2020-05-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('referal_level', models.PositiveIntegerField()),
                ('referal_up', models.PositiveIntegerField(default=0)),
                ('referal_down', models.PositiveIntegerField(default=0)),
                ('refer_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('transfered_amount', models.FloatField(default=0)),
                ('referal_code', models.CharField(max_length=50, null=True)),
                ('transaction_code', models.CharField(max_length=200, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('referal_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referal_username', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
