# Generated by Django 3.0.5 on 2020-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='referal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refer',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
