# Generated by Django 3.0.5 on 2020-07-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200712_1213'),
        ('referral', '0002_auto_20200503_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='referal_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referal_username', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='refer',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
        migrations.AlterModelTable(
            name='refer',
            table='refer',
        ),
    ]
