# Generated by Django 3.0.5 on 2020-07-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(db_column='agency_code', on_delete=django.db.models.deletion.PROTECT, to='agencies.Agency', to_field='code')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
    ]
