# Generated by Django 3.0.5 on 2020-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('website', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'angencies',
            },
        ),
    ]
