# Generated by Django 3.0.5 on 2020-07-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_auto_20200712_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('locations', models.CharField(blank=True, max_length=100, null=True)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('date_dispatch', models.DateTimeField(blank=True, null=True)),
                ('out_of_delivery', models.BooleanField(default=False)),
                ('user_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_delivery', to='staff.Staff')),
                ('user_distributer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_distributer', to='staff.Staff')),
                ('user_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_staff', to='staff.Staff')),
            ],
            options={
                'db_table': 'trackers',
            },
        ),
    ]
